name: CD

on:
  push:
    branches: [ "master" ]

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Pull Docker image
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker pull $DOCKER_USERNAME/banco_api
    - name: Delete Old Container
      run: sudo docker rm -f banco_api || true
    - name: Run Docker Container
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker run -d -p 8000:8000 --name banco_api $DOCKER_USERNAME/banco_api
